### ISSUE TITLE
#2 Add JS image compression

### ISSUE THREAD

**Issue by RoyMurphy** [RoyMurphy/Veribit#2]
*This enhancement has a bounty of 1.25 BSV

Before the image is uploaded, prepare the image for compression.
Target size should be 96kb (This works well for CityOnChain) for each single image.
This works around the UTXO speed limit issue and will fit into a single tx without concatenation.
I'm thinking something similar to https://www.npmjs.com/package/browser-image-compression

**Comment by RoyMurphy** [comment]
I'm wondering if there's an AVIF Javascript converter out there?
I know it's not officially supported by most browsers yet but we're building future tech.
Might as well stay cutting edge for quality/compression and figure out the browser issue, or build a solution. I'd be happy to hear some feedback on this.

**Comment by gWOLF3** [comment]
Why not simply use the browser-image-compression npm package to accomplish this? 

Ultimately, if the image targets you are shooting for is already under 100kb, it won't make a big difference. If what you are asking for is just a image of passport or drivers license ID, I think you do not need to worry so much about SOA compression. I would instead prioritize something that is well supported and tested.

**Comment by RoyMurphy** [comment]
Yes, you're right. The best KYC experience I've had was with the N26 verification process.
I believe they use https://www.npmjs.com/package/browser-image-compression with a max target of 6MB processing before upload. Having seen the relative quality of the 96kb reduced CityOnChain city images, I'm sure this will be fine without going too unnecessarily exotic. I will be integrating an AI reader for stage 1 doc cross referencing at some point, so as long as it's both human readable and AI decipherable it should be okay.

**Comment by Kagami** [comment]
>I'm wondering if there's an AVIF Javascript converter out there?

Currently no according to my knowledge, but could be pretty interesting to do one. I did client-side WebM encoder (VP8/Opus) in the past: https://github.com/Kagami/webm.js

Do you want it to be pure client-side? It's pretty easy to compress JPEG/PNG on a client, they don't require too much computational resources. But compressing single AVIF frame of average resolution might require 20-40 seconds and a lot of RAM, using native code (libaom). So port of libaom to browser could be pretty heavyweight in terms of resources required for it to work.

It's possible to port SVT-AV1/rav1e (alternative AV1 encoders) instead though, they should be faster. Quality could be a bit lower, those encoders have a bit worse quality/compression ratio than libaom, at least according to my tests: https://github.com/Kagami/av1-bench But probably not much.

So if you want client-side only AVIF encoding, rav1e is probably the best way to go. Otherwise, with the help of the server SVT-AV1 might be better choice because of better compression. libaom requires too much memory for big images so probably not that attractive even on server. I have bug reports regarding RAM usage for my go-avif encoder: https://github.com/Kagami/go-avif/issues/1

**Comment by RoyMurphy** [comment]
Thank you Kagami. Yes I saw the link that Derek posted yesterday which piqued my interest.
The encoding would have to be client-side in this specific case as the site will be hosted directly from the blockchain in a serverless environment. I will dig into your repo as I have a big interest in learning more and pushing the boundaries. For this project, stability and security is key, so I think we'll be heading towards the npm-js browser-image-compression solution or something very similar. I would love to use go-avif on another project though soon as your work is very impressive. Thank you again for your response, please keep in touch.

**Comment by RoyMurphy** [comment]
Completed.
